[package]
name = "rdm-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "snag"
path = "src/main.rs"

[dependencies]
rdm-core = { path = "../core" }
rdm-media = { path = "../media" }
rdm-bridge = { path = "../bridge" }
rdm-engine = { path = "../engine" }
iced = { version = "0.14", features = ["tokio", "image", "qr_code"] }
tokio.workspace = true
futures-util.workspace = true
chrono.workspace = true
tray-icon = "0.26.0"
tauri-winrt-notification = "0.8.1"
winreg = "0.56.0"

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
winresource = "0.1.31"
