[package]
name = "rdm-engine"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
reqwest.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
percent-encoding.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
axum.workspace = true
tempfile.workspace = true
