[package]
name = "rdm-core"
version.workspace = true
edition.workspace = true

[dependencies]
rdm-engine = { path = "../engine" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
axum.workspace = true
tempfile.workspace = true
futures-util.workspace = true
